# Generated by Django 5.1.4 on 2024-12-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('d_criacao', models.DateTimeField(auto_now_add=True)),
                ('d_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
