# Generated by Django 5.1.4 on 2025-02-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
    ]
